Resources:
  #####
  # This Authorizer is used for validating the JWT token before invoking the lambda
  #####
  authApiGatewayAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: CognitoUserPool
      Type: COGNITO_USER_POOLS
      IdentitySource: method.request.header.Authorization
      RestApiId:
        Ref: ApiGatewayRestApi
      ProviderARNs:
        - !GetAtt mfaAuthUserPool.Arn