Resources:
  mfaAuthUserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      UserPoolName: mfa-auth-${opt:stage}-user-pool
  
  mfaAuthUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain 
    Properties:
      UserPoolId: !Ref mfaAuthUserPool
      Domain: mfa-auth-${opt:stage}-user-pool-domain

  mfaAuthUserPoolResourceServer:
    Type: AWS::Cognito::UserPoolResourceServer
    Properties:
      UserPoolId: !Ref mfaAuthUserPool
      Identifier: ${self:custom.resourceServer.name}
      Name: mfa-auth-${opt:stage}-user-pool-resource-server
      Scopes:
        - ScopeName: ${self:custom.resourceServer.scopes.read}
          ScopeDescription: "A read placeholder scope"
        - ScopeName: ${self:custom.resourceServer.scopes.write}
          ScopeDescription: "A write placeholder scope"
          
Outputs:
  UserPoolId:
    Value:
      Ref: mfaAuthUserPool
  
  UserPoolDomain:
    Value:
      Ref: mfaAuthUserPoolDomain
  
  UserPoolArn:
    Value: !GetAtt mfaAuthUserPool.Arn
  
  UserPoolResourceServer:
    Value:
      Ref: mfaAuthUserPoolResourceServer