service: aws-java-maven

provider:
  name: aws
  runtime: java8
  environment:
    KEY_ARN: !GetAtt lambdaKey.Arn
    USER_POOL_ID: !Ref mfaAuthUserPool
    USER_POOL_RESOURCE_SERVER: !Ref mfaAuthUserPoolResourceServer
    TOKEN_DURATION: 30

region: us-east-1

plugins:
  - serverless-aws-documentation

# you can add packaging information here
package:
  artifact: target/hcqis-auth-dev.jar

# These are our API models for swagger
custom:
  client:
    distributionFolder: build/swagger-ui
  documentation:
    models:
      -
        name: "Registration"
        description: "This is a registration"
        contentType: "application/json"
        schema:
          type: "object"
          properties:
            user:
              type: "string"
            emailAddress:
              type: "string"
            activationDate:
              type: "string"
            duration:
              type: "integer"
            mfaDeviceId:
              type: "string"
      -
        name: "RegistrationError"
        description: "This is an registration error"
        contentType: "application/json"
        schema:
          type: "object"
          properties:
            errorMessage:
              type: "string"
              
functions:
  register:
    handler: org.hcqis.RegistryHandler
    role: lambdaRole
    events:
      - http:
          path: /v1/registration
          method: put
          cors: true
          # private: true
          documentation:
            summary: "Register for an authentication jwt"
            description: "Register for an authentication jwt"
            tags:
              - "Registration"
            requestBody:
              description: "The registry details, namely a user id and an email address where a presigned url will be sent for jwt delivery"
            requestModels:
              "application/json": "Registration"
            methodResponses:
              -
                statusCode: "200"
                responseBody:
                  description: "The registry metadata"
                responseModels:
                  "application/json": "Registration"
              -
                statusCode: "400"
                responseModels:
                  "application/json": "RegistrationError"
  registerMfa:
    handler: org.hcqis.MfaRegistryHandler
    role: lambdaRole
  sampler:
    handler: org.hcqis.SampleAppHandler
    role: lambdaRole
    events:
      - http:
          path: /v1/sampler
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: authApiGatewayAuthorizer

resources:
  # IAM
  - ${file(provision/iam-lambda-role.yml)}
  # KMS
  - ${file(provision/kms-lambda-key.yml)}
  # Cognito
  - ${file(provision/cognito-user-pool.yml)}
  - ${file(provision/cognito-identity-pool.yml)}
  # API Gateway
  - ${file(provision/api-gateway.yml)}
